import {useEffect,useState} from 'react';import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar} from 'recharts';
import type {HistoryRow} from '../types';import {fmtTime} from '../types';import {api,downloadJSON} from '../api';import {Panel,Metric,Empty} from './Widgets';
export default function Analytics({page,refresh}:{page:'Progress'|'History';refresh:number}){
 const [days,setDays]=useState(30),[mode,setMode]=useState('camera'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[detail,setDetail]=useState<any>(null);
 useEffect(()=>{let live=true;setError('');api('/progress?days='+days+'&mode='+mode).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[days,mode,refresh]);
 const rows:HistoryRow[]=data?.sessions||[];const chart=rows.map(r=>({date:new Date(r.started).toLocaleDateString(undefined,{month:'short',day:'numeric'}),form:r.summary.average_form,reps:r.summary.total_reps,rom:r.summary.average_rom,minutes:Math.round(r.duration/6)/10,tempo:r.summary.average_tempo}));
 const open=async(id:string)=>{try{setDetail(await api('/sessions/'+id));}catch(e){setError(String(e));}};
 return <div className="page-content"><div className="section-heading"><div><h1>{page==='Progress'?'Your progress, in motion.':'Every session tells a story.'}</h1><p>Measured sessions. Meaningful improvements.</p></div><div className="row"><select aria-label="History source" value={mode} onChange={e=>setMode(e.target.value)}><option value="camera">Camera workouts</option><option value="demo">Demo workouts</option></select><select aria-label="Date range" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option><option value={0}>All time</option></select></div></div>
 {error&&<p role="alert" className="error">{error}</p>}{!data?<p>Loading analytics…</p>:!rows.length?<Empty text={`Finish a ${mode} workout to see your history and progress here.`}/>:<><div className="summary-strip"><Metric label="Sessions" value={data.session_count}/><Metric label="Total repetitions" value={data.total_reps}/><Metric label="Training time" value={fmtTime(data.duration)}/><Metric label="Active days" value={data.active_days}/></div>
 {page==='Progress'&&<div className="chart-grid">{[['form','Form Score Trend','/100'],['reps','Repetitions by Session','reps'],['rom','Range of Motion','degrees'],['minutes','Workout Duration','minutes'],['tempo','Average Rep Tempo','seconds']].map(([key,title,unit])=><Panel key={key} title={title}><p className="chart-unit">{unit}</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid stroke="#183047" strokeDasharray="3 3"/><XAxis dataKey="date" stroke="#7995ae" fontSize={11}/><YAxis stroke="#7995ae" fontSize={11}/><Tooltip contentStyle={{background:'#102135',border:'1px solid #294154'}}/><Line dataKey={key} stroke="#23dfb8" strokeWidth={2} dot={{r:4}} connectNulls={false}/></LineChart></ResponsiveContainer></div></Panel>)}<Panel title="Exercise Volume"><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.volume}><XAxis dataKey="exercise" stroke="#7995ae" fontSize={10}/><YAxis stroke="#7995ae"/><Tooltip contentStyle={{background:'#102135'}}/><Bar dataKey="reps" fill="#2abbe8" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Panel></div>}
 <Panel title="Workout history" action={<button onClick={()=>downloadJSON(rows,'motionmind-history.json')}>Export view</button>}><div className="table-wrap"><table><thead><tr><th>Date</th><th>Duration</th><th>Exercises</th><th>Reps</th><th>Form</th><th>ROM</th><th>Est. kcal</th><th/></tr></thead><tbody>{[...rows].reverse().map(r=><tr key={r.id}><td>{new Date(r.started).toLocaleString()}</td><td>{fmtTime(r.duration)}</td><td>{[...new Set(r.summary.segments.map(s=>s.exercise.replaceAll('_',' ')))].join(', ')}</td><td>{r.summary.total_reps}</td><td>{r.summary.average_form??'—'}</td><td>{r.summary.average_rom??'—'}°</td><td>{r.summary.calories_estimate}</td><td><button onClick={()=>open(r.id)}>Details</button></td></tr>)}</tbody></table></div></Panel></>}
 {detail&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-label="Session details"><header><h2>Session details</h2><button onClick={()=>setDetail(null)}>Close</button></header>{detail.summary.insights?.map((i:string)=><p key={i}>{i}</p>)}{detail.sets.map((s:any,i:number)=><div className="detail-set" key={i}><h3>{s.exercise.replaceAll('_',' ')} · Set {s.set}</h3><p>{s.metrics.reps} reps · {s.metrics.hold_seconds}s hold · Form {s.metrics.average_form??'—'}</p>{s.repetitions.map((r:any,j:number)=><p className="muted" key={j}>Rep {r.number}: {r.rom}° ROM · {r.out_seconds}s / {r.back_seconds}s · Score {r.form_score}</p>)}</div>)}<button onClick={()=>downloadJSON(detail,'motionmind-session.json')}>Export session</button></div></div>}
 </div>;
}
