import {useState} from 'react';import {ArrowUp,ArrowDown,Plus,Trash2,X} from 'lucide-react';
import type {Exercise,Plan,PlanItem} from '../types';import {api} from '../api';
export default function PlanEditor({plan,exercises,onClose,onSave}:{plan:Plan;exercises:Exercise[];onClose:()=>void;onSave:(p:Plan)=>void}){
 const [name,setName]=useState(plan.name),[items,setItems]=useState<PlanItem[]>(plan.items.map(i=>({...i}))),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const move=(i:number,d:number)=>{const next=[...items];[next[i],next[i+d]]=[next[i+d],next[i]];setItems(next);};
 const save=async(copy=false)=>{setBusy(true);try{const p=await api<Plan>('/workouts'+(copy?'':`/${plan.id}`),copy?'POST':'PUT',{name,items});onSave(p);}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="Edit workout plan"><header><h2>Build your session</h2><button aria-label="Close plan editor" onClick={onClose}><X size={20}/></button></header><p className="muted">Arrange your exercises, sets, and targets. Plank targets are seconds.</p><label>Plan name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label>
 <div className="plan-labels"><span>Exercise</span><span>Sets</span><span>Reps / sec</span><span>Order</span></div>
 {items.map((item,i)=><div className="plan-edit-row" key={i}><select aria-label={`Exercise ${i+1}`} value={item.exercise} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,exercise:e.target.value}:x))}>{exercises.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><input aria-label={`Sets ${i+1}`} type="number" min="1" max="20" value={item.sets} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,sets:Number(e.target.value)}:x))}/><input aria-label={`Target ${i+1}`} type="number" min="1" max="300" value={item.reps} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,reps:Number(e.target.value)}:x))}/><div className="row gap-1"><button aria-label={`Move exercise ${i+1} up`} disabled={!i} onClick={()=>move(i,-1)}><ArrowUp size={14}/></button><button aria-label={`Move exercise ${i+1} down`} disabled={i===items.length-1} onClick={()=>move(i,1)}><ArrowDown size={14}/></button><button aria-label={`Remove exercise ${i+1}`} disabled={items.length===1} onClick={()=>setItems(items.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></div></div>)}
 <button onClick={()=>setItems([...items,{exercise:'squat',sets:3,reps:12}])} disabled={items.length>=30}><Plus size={16}/> Add exercise</button>{error&&<p role="alert" className="error">{error}</p>}<footer><button onClick={()=>save(true)} disabled={busy}>Save as new plan</button><button className="primary" onClick={()=>save()} disabled={busy||!name.trim()}>Save plan</button></footer></div></div>;
}
