import {useState,useEffect,useRef,useCallback} from 'react';
import {Activity,House,Dumbbell,ChartNoAxesCombined,Bot,History,Settings as SettingsIcon,Video,Play,Pause,Square,ChevronRight,ChevronDown,Check,ScanLine,AudioLines,BrainCircuit,Timer,Flame,Target,Lightbulb,SlidersHorizontal,Download,Trash2,ShieldCheck,Zap,ArrowUpRight,Search,CheckCircle2,Wifi,WifiOff,RotateCw,X} from 'lucide-react';
import {api,downloadJSON} from './api';import {DEFAULT_SETTINGS,fmtTime,type Settings,type Exercise,type Plan,type SessionState,type Motion,type Landmark,type HistoryRow} from './types';
import {useCamera} from './vision/useCamera';import {demoPose} from './vision/demo';import {Overlay,Motion3D,type PoseBuffer} from './components/PoseViews';
import {Panel,Ring,Metric,Empty} from './components/Widgets';import PlanEditor from './components/PlanEditor';import Analytics from './components/Analytics';
const NAV=[{name:'Home',icon:House},{name:'Workout',icon:Dumbbell},{name:'Progress',icon:ChartNoAxesCombined},{name:'AI Coach',icon:Bot},{name:'History',icon:History},{name:'Settings',icon:SettingsIcon}];
export default function App(){
 const [page,setPage]=useState('Home'),[exercises,setExercises]=useState<Exercise[]>([]),[plans,setPlans]=useState<Plan[]>([]),[planId,setPlanId]=useState(1);
 const [settings,setSettings]=useState<Settings>(DEFAULT_SETTINGS),[profile,setProfile]=useState({name:'Athlete',weight_kg:70});
 const [source,setSource]=useState<'camera'|'demo'>('demo'),[session,setSession]=useState<SessionState|null>(null),[motion,setMotion]=useState<Motion|null>(null),[socketStatus,setSocketStatus]=useState('idle');
 const [backend,setBackend]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[editPlan,setEditPlan]=useState(false),[library,setLibrary]=useState(false),[query,setQuery]=useState(''),[selected,setSelected]=useState<Exercise|null>(null);
 const [summary,setSummary]=useState<HistoryRow|null>(null),[refresh,setRefresh]=useState(0),[diagnostics,setDiagnostics]=useState<any>(null),[lastSession,setLastSession]=useState<HistoryRow|null>(null);
 const sessionRef=useRef(session);sessionRef.current=session;const settingsRef=useRef(settings);settingsRef.current=settings;
 const buffer=useRef<PoseBuffer>({pose:[],predicted:[],world:[],aspect:16/9});const socket=useRef<WebSocket|null>(null),awaiting=useRef(false),lastUI=useRef(0),lastVoice=useRef('');const droppedSocket=useRef(0);
 const load=useCallback(async()=>{try{const [health,ex,pl,pr,active,hist]=await Promise.all([api('/health'),api<Exercise[]>('/exercises'),api<Plan[]>('/workouts'),api('/profile'),api<SessionState|null>('/sessions/active'),api<HistoryRow[]>('/history?mode=camera')]);setBackend(health.status==='ok');setExercises(ex);setPlans(pl);if(pl.length)setPlanId(pl[0].id);setProfile({name:pr.name,weight_kg:pr.weight_kg});setSettings({...DEFAULT_SETTINGS,...pr.settings});if(active){setSession(active);setSource(active.mode);}setLastSession(hist.find(s=>s.status==='finished')||null);setError('');}catch(e){setBackend(false);setError('Backend unavailable. Start the backend, then click Retry. '+String(e));}},[]);
 useEffect(()=>{load();},[load]);
 useEffect(()=>{document.documentElement.dataset.theme=settings.theme;},[settings.theme]);
 const onPose=useCallback((p:Landmark[],t:number,aspect:number,world:Landmark[]=[])=>{
  buffer.current.pose=p;buffer.current.world=world;buffer.current.aspect=aspect;
  const current=sessionRef.current,ws=socket.current;
  if(!current||current.status!=='active'||!ws||ws.readyState!==WebSocket.OPEN)return;
  if(awaiting.current||ws.bufferedAmount>32000){droppedSocket.current++;return;}
  const points=p.length===33?p:Array.from({length:33},()=>({x:0,y:0,z:0,visibility:0}));
  awaiting.current=true;ws.send(JSON.stringify({type:'pose',timestamp:t,aspect,landmarks:points.map(q=>({x:q.x,y:q.y,z:q.z,visibility:q.visibility??0}))}));
 },[]);
 const camera=useCamera(settings,onPose);
 useEffect(()=>{
  if(source!=='demo')return;const started=performance.now();
  const interval=setInterval(()=>{const current=sessionRef.current;const t=performance.now();const p=demoPose(current?.exercise||'squat',(t-started)/1000);onPose(p,t/1000,16/9);},80);
  return()=>clearInterval(interval);
 },[source,session?.exercise,onPose]);
 useEffect(()=>{
  if(!session?.session_id)return;let cancelled=false,retry:ReturnType<typeof setTimeout>|undefined,attempt=0;const sid=session.session_id;
  const connect=()=>{
   if(cancelled)return;setSocketStatus('connecting');const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/motion`);socket.current=ws;
   ws.onopen=()=>{attempt=0;awaiting.current=false;ws.send(JSON.stringify({type:'init',session_id:sid}));setSocketStatus('connected');};
   ws.onmessage=({data})=>{
    const result=JSON.parse(data);awaiting.current=false;
    if(result.type==='error'){setError(result.message);return;}
    if(result.state){sessionRef.current=result.state;const now=performance.now();if(result.type==='state'||now-lastUI.current>180||result.rep_event||result.state.set_complete){setSession(result.state);if(result.type==='motion')setMotion(result);lastUI.current=now;}}
    if(result.pose){buffer.current.pose=result.pose;buffer.current.predicted=settingsRef.current.prediction?(result.prediction?.pose||[]):[];}
    if(result.feedback&&result.feedback!==lastVoice.current){lastVoice.current=result.feedback;if(settingsRef.current.voice&&'speechSynthesis'in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(result.feedback);utterance.rate=1;speechSynthesis.speak(utterance);}}
    if(result.rep_event&&settingsRef.current.sound){try{const ctx=new AudioContext();const osc=ctx.createOscillator(),gain=ctx.createGain();gain.gain.value=.04;osc.frequency.value=660;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.09);osc.onended=()=>ctx.close();}catch{}}
   };
   ws.onerror=()=>setSocketStatus('error');ws.onclose=()=>{awaiting.current=false;if(!cancelled){setSocketStatus('reconnecting');retry=setTimeout(connect,Math.min(8000,700*2**attempt++));}};
  };connect();
  return()=>{cancelled=true;if(retry)clearTimeout(retry);socket.current?.close();socket.current=null;awaiting.current=false;setSocketStatus('idle');};
 },[session?.session_id]);
 useEffect(()=>{if(page!=='Settings')return;api('/diagnostics').then(setDiagnostics).catch(()=>{});const timer=setInterval(()=>api('/diagnostics').then(setDiagnostics).catch(()=>{}),3000);return()=>clearInterval(timer);},[page]);
 const plan=plans.find(p=>p.id===planId)||plans[0],currentExercise=exercises.find(e=>e.id===(session?.exercise||plan?.items[0]?.exercise||'squat'));
 const perform=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const start=()=>perform(async()=>{if(!plan)throw Error('Create a workout plan first.');if(source==='camera'&&camera.status!=='ready')throw Error('Connect the camera and wait for the pose model before starting.');setMotion(null);setSummary(null);const s=await api<SessionState>('/workouts/'+plan.id+'/start','POST',{mode:source});sessionRef.current=s;setSession(s);setPage('Workout');});
 const command=(c:string)=>perform(async()=>{if(!session)return;const result=await api('/sessions/'+session.session_id+'/command','POST',{command:c});setSession(result.state);sessionRef.current=result.state;if(c==='next'){setMotion(null);buffer.current.predicted=[];}});
 const finish=()=>perform(async()=>{if(!session)return;const saved=await api<HistoryRow>('/sessions/'+session.session_id+'/finish','POST');sessionRef.current=null;setSession(null);setMotion(null);setSummary(saved);setRefresh(v=>v+1);if(saved.mode==='camera')setLastSession(saved);if('speechSynthesis'in window)speechSynthesis.cancel();});
 const saveSettings=()=>perform(async()=>{await api('/profile','PUT',{...profile,settings});setNotice('Settings saved. Reconnect the camera to apply device or resolution changes.');});
 const clearData=(all=false)=>perform(async()=>{if(!confirm(all?'Delete all local workout history, plans and profile settings?':'Delete all camera and demo workout history?'))return;await api(all?'/data':'/history','DELETE');setSummary(null);setLastSession(null);setRefresh(v=>v+1);setNotice('Local data deleted.');if(all)await load();});
 const sourceChange=(mode:'camera'|'demo')=>{if(session)return;camera.stop();buffer.current.pose=[];buffer.current.predicted=[];setMotion(null);setSource(mode);};
 const updateSetting=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(s=>({...s,[key]:value}));
 const good=motion?.valid;const score=good?motion.form_score:null;
 const insightList=summary?.summary.insights||lastSession?.summary.insights||[];
 return <div className="app-shell"><aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setPage('Home');}}><div className="brand-symbol"><Activity size={29}/></div><div><strong>MotionMind</strong><small>AI Workout Assistant</small></div></a><div className="nav-label">YOUR WORKSPACE</div><nav>{NAV.map(({name,icon:Icon})=><button key={name} className={page===name?'nav-item active':'nav-item'} onClick={()=>setPage(name)}><Icon size={20}/><span>{name}</span>{page===name&&<i/>}</button>)}</nav><div className="sidebar-promo"><div className="orbit"><Activity size={50}/></div><h3>Better form.<br/>Stronger you.</h3><p>Understand your movement.<br/>Build your next best.</p><span><ShieldCheck size={14}/> Private by design</span></div><div className="sidebar-bottom"><span className={backend?'status-dot':'status-dot offline'}/>{backend?'Local engine online':'Engine offline'}<small>v1.0</small></div></aside>
 <main><header className="topbar"><div className="greeting"><div className="avatar">{profile.name[0]?.toUpperCase()}</div><div><h2>Let's move, {profile.name}.</h2><p>Build a healthier, stronger you. One rep at a time.</p></div></div><div className="header-right"><div className="camera-badge"><Video size={19}/><div><strong>{source==='demo'?'Demo environment':camera.status==='ready'?'Camera connected':'Camera offline'}</strong><small>{source==='demo'?'Synthetic pose stream':camera.diagnostics.resolution+' · '+camera.diagnostics.cameraFPS+' FPS requested'}</small></div></div><button className="profile-button" onClick={()=>setPage('Settings')}><span className="profile-avatar">{profile.name.slice(0,1)}</span><span>{profile.name}<small>Personal workspace</small></span><ChevronDown size={14}/></button></div></header>
 {error&&<div role="alert" className="banner error">{error}{!backend&&<button onClick={load}>Retry</button>}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={14}/></button></div>}
 {notice&&<div className="banner success">{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 <div className={page==='Home'||page==='Workout'?'dashboard':'dashboard hidden'}>
 <div className="dashboard-toolbar"><div className="row"><span className="eyebrow">MOTION INTELLIGENCE</span><span className="pill"><span className="status-dot"/> CPU-first</span></div><div className="row"><div className="segmented"><button className={source==='demo'?'chosen':''} disabled={!!session} onClick={()=>sourceChange('demo')}>Demo</button><button className={source==='camera'?'chosen':''} disabled={!!session} onClick={()=>sourceChange('camera')}>Webcam</button></div>{source==='camera'&&<button onClick={()=>camera.status==='ready'?camera.stop():camera.start()} disabled={camera.status==='loading'}><Video size={15}/>{camera.status==='ready'?'Stop camera':camera.status==='loading'?'Loading model…':'Connect camera'}</button>}<span className="connection" title="Backend connection">{socketStatus==='connected'?<Wifi size={15}/>:<WifiOff size={15}/>} {session?socketStatus:'Ready to start'}</span></div></div>
 <div className="top-grid"><div className="main-track"><div className="visual-grid"><section className="live-panel"><div className="live-top"><span className={'live-label '+(source==='demo'?'demo':'')}><i/>{source==='demo'?'DEMO MODE':'LIVE FEED'}</span><span className="exercise-badge"><ScanLine size={15}/>{motion?.recognition||currentExercise?.name||'Pose tracking'}{!session&&' · preview'}</span></div>
 <video ref={camera.videoRef} autoPlay playsInline muted className={source==='camera'?'camera-video':'camera-video invisible'}/><Overlay buffer={buffer} visible={settings.skeleton} demo={source==='demo'}/>
 {source==='camera'&&camera.status!=='ready'&&<div className="camera-empty"><Video size={38}/><h3>{camera.status==='loading'?'Preparing your pose model…':'Your space. Your pace.'}</h3><p>{camera.error||'Connect a camera to start tracking your movement.'}</p><button className="primary" onClick={camera.start} disabled={camera.status==='loading'}>Connect camera</button></div>}
 <div className="live-stats"><div><small>{source==='demo'?'SOURCE':'INFERENCE FPS'}</small><strong>{source==='demo'?'Synthetic':camera.diagnostics.inferenceFPS||'—'}</strong></div><div><small>MODEL</small><strong>{source==='demo'?'Pose fixture':'MediaPipe Lite'}</strong></div><div><small>{source==='demo'?'ANALYSIS':'INFERENCE'}</small><strong>{source==='demo'?(motion?.processing_ms??'—'):camera.diagnostics.latency||'—'} <em>ms</em></strong></div></div>
 <div className="live-bottom"><span><ScanLine size={14}/> {motion?.phase||'Ready when you are'}</span><span>{good?Math.round(motion.confidence*100)+'% landmark visibility':currentExercise?.view||'Full body in frame'}</span></div></section>
 <Panel title="3D Motion View" icon={<ScanLine size={15}/>} className="motion-panel"><Motion3D buffer={buffer} prediction={settings.prediction}/></Panel></div>
 <section className="metrics-bar"><div className="rep-metric"><Ring value={session?Math.min(100,((motion?.reps||0)/session.target)*100):0} label="target" size={62}/><div><strong>{session?.exercise==='plank'?Math.floor(motion?.hold_seconds||0):motion?.reps||0}</strong><small>{session?.exercise==='plank'?'Hold seconds':'Repetitions'}</small></div></div><Metric label="CURRENT SET" value={session?`${session.set} / ${session.sets}`:'—'}/><Metric label="TEMPO" value={motion?.tempo?`${motion.tempo[0].toFixed(1)} / ${motion.tempo[1].toFixed(1)} s`:'—'} note="Toward peak / return"/><Metric label="ROM" value={good?`${motion.rom?.current||0}°`:'—'} note="Observed angle span"/><Metric label="EST. ENERGY" value={<>{session?.summary.calories_estimate||0} <em>kcal</em></>} note="MET estimate"/><Metric label="ACTIVE TIME" value={fmtTime(session?.duration)} note={session?.status||'Not started'}/></section>
 <div className="workout-controls"><div><span className="status-dot"/><strong>{session?(session.complete?'Session targets reached':session.set_complete?'Set complete. Take a breath.':session.status==='paused'?'Workout paused':session.exercise_name+' · '+currentExercise?.view):'Your next session starts here.'}</strong><small>{session?'Finish & save anytime, or continue your plan.':'Choose a source and a plan, then press Start workout.'}</small></div><div className="row">{!session?<button className="primary" disabled={!backend||busy} onClick={start}><Play size={16}/> Start workout</button>:<>{!session.set_complete&&<button onClick={()=>command(session.status==='active'?'pause':'resume')} disabled={busy}>{session.status==='active'?<Pause size={15}/>:<Play size={15}/>} {session.status==='active'?'Pause':'Resume'}</button>}{!session.complete&&<button onClick={()=>{if(session.set_complete||confirm('End this set early and move to the next set?'))command('next');}} disabled={busy}>{session.set_complete?'Next set':'Skip set'}<ChevronRight size={14}/></button>}<button className="primary" onClick={finish} disabled={busy}><Square size={13}/> Finish & save</button></>}</div></div>
 </div><aside className="analysis-stack"><Panel title="Form Analysis" icon={<Activity size={16}/>}><div className="score-header"><Ring value={score} label="/ 100"/><div><strong className="mint">{score===null?'Awaiting pose':score>=90?'Excellent':score>=80?'Good form':score>=70?'Needs adjustment':'Review your form'}</strong><p>Transparent heuristic score</p></div></div><div className="analysis-list">{[['Joint angle',good?`${motion.angle}°`:'—'],['Torso from vertical',good?`${motion.angles?.torso}°`:'—'],['Tracked side',good?motion.side:'—'],['Average rep ROM',motion?.rom?.average!=null?`${motion.rom.average}°`:'—']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><details><summary>How this score works</summary><p>Alignment 30% · ROM 25% · Stability 20% · Tempo 15% · Symmetry 10%. Missing components are excluded and weights renormalized.</p>{motion?.score_parts&&Object.entries(motion.score_parts).map(([k,v])=><div className="score-part" key={k}><span>{k}</span><span>{v??'Not available'}</span></div>)}</details></Panel>
 <Panel title="Real-time Feedback" icon={<AudioLines size={16}/>}><div className="feedback-box"><CheckCircle2 size={24}/><p>{motion?.feedback||'Start a workout to receive live coaching from your tracked movement.'}</p></div></Panel>
 <Panel title="Next Movement Prediction" icon={<BrainCircuit size={16}/>}><div className="prediction"><Activity size={41}/><div><small>PROJECTED MOTION</small><strong>{settings.prediction?(motion?.prediction?.label||'Waiting for motion'):'Prediction disabled'}</strong><p>{settings.prediction&&motion?.prediction?.eta!=null?'Threshold ETA ~'+motion.prediction.eta+'s':'Trajectory baseline'}</p></div></div>{settings.prediction&&motion?.prediction?.reliability!=null&&<p className="tiny">Direction consistency: {motion.prediction.reliability}% · heuristic, not model confidence</p>}</Panel></aside></div>
 <div className="bottom-grid"><Panel title="Workout Plan" icon={<Dumbbell size={16}/>} action={<button className="text-button" disabled={!!session||!plan} onClick={()=>setEditPlan(true)}>Edit plan</button>}><select className="plan-select" aria-label="Workout plan" value={planId} disabled={!!session} onChange={e=>setPlanId(Number(e.target.value))}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="plan-list">{plan?.items.map((item,i)=><div className={i===(session?.exercise_index??0)?'plan-row selected':'plan-row'} key={i}><span className="number">{i+1}</span><strong>{exercises.find(e=>e.id===item.exercise)?.name}</strong><span>{item.sets} × {item.reps}{item.exercise==='plank'?'s':''}</span>{session&&i<session.exercise_index?<Check size={16}/>:<span className="circle"/>}</div>)}</div></Panel>
 <Panel title="Exercise Library" icon={<Activity size={16}/>} action={<button className="text-button" onClick={()=>setLibrary(true)}>View all <ArrowUpRight size={13}/></button>}><p className="muted tiny">Find your movement. Learn the form.</p><div className="exercise-grid">{exercises.filter(e=>['squat','pushup','lunge','plank','shoulder_press','bicep_curl','tricep_extension','jumping_jack'].includes(e.id)).map(e=><button key={e.id} className={'exercise-card '+(currentExercise?.id===e.id?'selected':'')} onClick={()=>setSelected(e)}><Activity size={25}/><span>{e.name}</span></button>)}</div></Panel>
 <Panel title="Session Progress" icon={<Target size={16}/>}><div className="progress-head"><Ring value={session?.progress||0} label="% complete" size={82}/><div><strong>{session?.complete?'Targets reached':'Keep showing up'}</strong><p>{session?.summary.total_reps||0} total reps</p></div></div><div className="progress-row"><span>Current set</span><strong>{session?`${session.set} / ${session.sets}`:'—'}</strong></div><div className="progress-track"><i style={{width:(session?.progress||0)+'%'}}/></div><div className="progress-row"><Timer size={16}/><span>Active training</span><strong>{fmtTime(session?.duration)}</strong></div><p className="tiny muted">Progress is weighted equally across planned sets.</p></Panel>
 <Panel title="Personalized Insights" icon={<Lightbulb size={16}/>}><div className="insights">{insightList.length?insightList.slice(0,3).map((t,i)=><div key={i}><ArrowUpRight size={17}/><p>{t}</p></div>):<><div><Lightbulb size={19}/><p>Finish your first workout to unlock insights based on your actual session.</p></div><div><ShieldCheck size={19}/><p>Historical comparisons appear only when matching past workouts exist.</p></div></>}</div></Panel></div>
 <footer className="dashboard-footer">LIVE MOTION <i>→</i> UNDERSTAND <i>→</i> ANALYZE <i>→</i> PREDICT <i>→</i> IMPROVE</footer>
 </div>
 {(page==='Progress'||page==='History')&&<Analytics page={page} refresh={refresh}/>}
 {page==='AI Coach'&&<div className="page-content"><div className="section-heading"><div><h1>Your movement, understood.</h1><p>Rule-based coaching grounded in your session data.</p></div><span className="pill"><Bot size={15}/> Local coach</span></div>{!motion&&!lastSession?<Empty text="Start a workout to get current feedback, or finish one to review your results."/>:<div className="coach-grid"><Panel title="Current movement"><h2>{session?.exercise_name||'No active workout'}</h2><p>{motion?.feedback||'Your saved workout insights are shown alongside.'}</p><p className="muted">{motion?.valid?`Form score ${motion.form_score}/100 · ROM ${motion.rom?.current}°`:'No reliable live pose.'}</p></Panel><Panel title="Strengths & suggested improvements">{motion?.score_parts?Object.entries(motion.score_parts).filter(([,v])=>v!==null).map(([k,v])=><div className="coach-rule" key={k}><strong>{k}</strong><span>{(v||0)>=80?'Currently consistent':'Review this component'} · {v}/100</span></div>):<p>Track movement to review score components.</p>}</Panel><Panel title="Previous workout insights">{lastSession?.summary.insights?.map((x,i)=><p key={i}>{x}</p>)||<p>No completed camera workout yet.</p>}</Panel><Panel title="Next workout"><h3>{plan?.name}</h3><p>Repeat the saved plan to establish a comparable baseline.</p><button onClick={()=>setPage('Workout')}>Open workout <ChevronRight size={16}/></button></Panel></div>}</div>}
 {page==='Settings'&&<div className="page-content"><div className="section-heading"><div><h1>Made for your setup.</h1><p>Configure your camera, coaching and local workspace.</p></div><button className="primary" onClick={saveSettings} disabled={busy}><Check size={16}/> Save settings</button></div><div className="settings-grid"><Panel title="Profile & preferences" icon={<SlidersHorizontal size={16}/>}><label>Your name<input value={profile.name} maxLength={80} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Weight ({settings.units}) · calorie estimate<input type="number" min={settings.units==='kg'?20:44} max={settings.units==='kg'?350:772} value={Math.round(profile.weight_kg*(settings.units==='lb'?2.20462:1)*10)/10} onChange={e=>setProfile({...profile,weight_kg:Number(e.target.value)/(settings.units==='lb'?2.20462:1)})}/></label><label>Units<select value={settings.units} onChange={e=>updateSetting('units',e.target.value as 'kg'|'lb')}><option value="kg">Metric (kg)</option><option value="lb">Imperial (lb)</option></select></label><label>Theme<select value={settings.theme} onChange={e=>updateSetting('theme',e.target.value as 'midnight'|'slate')}><option value="midnight">Midnight blue</option><option value="slate">Slate</option></select></label></Panel>
 <Panel title="Camera & performance" icon={<Video size={16}/>}><label>Camera<select value={settings.cameraId} onChange={e=>updateSetting('cameraId',e.target.value)}><option value="">System default</option>{camera.devices.map((d,i)=><option key={d.deviceId} value={d.deviceId}>{d.label||'Camera '+(i+1)}</option>)}</select></label><button onClick={()=>camera.listDevices().catch(e=>setError(String(e)))}><RotateCw size={14}/> Refresh devices</button><label>Performance profile<select value={settings.performance} onChange={e=>{const p=e.target.value;setSettings(s=>({...s,performance:p,resolution:p==='performance'?'640x360':p==='quality'?'1920x1080':'1280x720',fps:p==='performance'?9:p==='quality'?18:12}));}}><option value="performance">Performance · 640 × 360</option><option value="balanced">Balanced · 1280 × 720</option><option value="quality">Quality · 1920 × 1080</option></select></label><label>Capture resolution<select value={settings.resolution} onChange={e=>updateSetting('resolution',e.target.value)}>{['640x360','1280x720','1920x1080'].map(v=><option key={v}>{v}</option>)}</select></label><label>Maximum inference FPS: {settings.fps}<input type="range" min="5" max="20" value={settings.fps} onChange={e=>updateSetting('fps',Number(e.target.value))}/></label><p className="tiny muted">Inference adapts to model latency. Video playback runs separately.</p>{camera.diagnostics.latency>100&&<p className="amber">Try Performance mode for lower latency on this device.</p>}</Panel>
 <Panel title="Live experience" icon={<Zap size={16}/>} >{([['skeleton','Skeleton overlay'],['prediction','Trajectory prediction'],['sound','Rep confirmation sound'],['voice','Voice coaching']] as const).map(([key,label])=><label className="toggle-label" key={key}><span>{label}</span><input type="checkbox" checked={settings[key]} onChange={e=>updateSetting(key,e.target.checked)}/></label>)}<p className="tiny muted">Voice uses your browser's speech service. Available voices and offline support depend on your device.</p></Panel>
 <Panel title="Data & privacy" icon={<ShieldCheck size={16}/>}><p>Video frames stay in your browser. Only pose coordinates and workout metrics reach the local backend. Raw footage and landmark sequences are not saved.</p><button onClick={()=>perform(async()=>downloadJSON(await api('/export'),'motionmind-export.json'))}><Download size={15}/> Export workout data</button><button className="danger mt-3" disabled={!!session} onClick={()=>clearData()}><Trash2 size={15}/> Delete workout history</button><button className="danger mt-3" disabled={!!session} onClick={()=>clearData(true)}>Delete all local data</button></Panel>
 <Panel title="Advanced diagnostics" className="wide"><div className="diagnostic-grid">{[['Camera FPS (requested)',camera.diagnostics.cameraFPS],['Inference FPS',camera.diagnostics.inferenceFPS],['Inference latency',camera.diagnostics.latency+' ms'],['Effective FPS target',camera.diagnostics.effectiveFPS],['Landmark visibility',motion?Math.round(motion.confidence*100)+'%':'—'],['Host CPU',diagnostics?.cpu_percent!=null?diagnostics.cpu_percent+'%':'—'],['Backend memory',diagnostics?.backend_memory_mb?diagnostics.backend_memory_mb+' MB':'—'],['Skipped worker frames',camera.diagnostics.dropped],['Skipped socket samples',droppedSocket.current],['WebSocket',socketStatus]].map(([k,v])=><Metric key={k} label={String(k)} value={v}/>)}</div><p className="tiny muted">Timing reflects this device, not a performance guarantee. Rendering is capped at 30 FPS for 3D; the overlay follows the browser display loop.</p></Panel></div></div>}
 <p className="safety-note">AI fitness guidance is informational and does not replace professional medical or fitness advice. Stop exercising if you experience pain, dizziness, or unusual symptoms.</p>
 </main>
 {editPlan&&plan&&<PlanEditor plan={plan} exercises={exercises} onClose={()=>setEditPlan(false)} onSave={p=>{setPlans(plans.some(x=>x.id===p.id)?plans.map(x=>x.id===p.id?p:x):[...plans,p]);setPlanId(p.id);setEditPlan(false);}}/>}
 {library&&<div className="modal-backdrop"><div className="modal library-modal" role="dialog" aria-label="Exercise library"><header><h2>Find your next movement</h2><button aria-label="Close library" onClick={()=>setLibrary(false)}><X size={18}/></button></header><div className="search-box"><Search size={16}/><input placeholder="Search exercises, muscles or categories…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="library-grid">{exercises.filter(e=>(e.name+e.category+e.muscles).toLowerCase().includes(query.toLowerCase())).map(e=><button className="library-card" key={e.id} onClick={()=>setSelected(e)}><Activity size={30}/><h3>{e.name}</h3><span>{e.category} · {e.difficulty}</span><p>{e.muscles}</p></button>)}</div></div></div>}
 {selected&&<div className="modal-backdrop top-modal"><div className="modal" role="dialog" aria-label="Exercise instructions"><header><h2>{selected.name}</h2><button aria-label="Close instructions" onClick={()=>setSelected(null)}><X size={18}/></button></header><span className="pill">{selected.category} · {selected.view}</span><h3>How to move</h3><p>{selected.instructions}</p><h3>Target muscles</h3><p>{selected.muscles}</p><h3>Tracking rules</h3><p>{selected.rep_logic}</p><p className="muted">{selected.tracking}</p><footer><button className="primary" disabled={!!session} onClick={()=>perform(async()=>{const p=await api<Plan>('/workouts','POST',{name:selected.name+' Practice',items:[{exercise:selected.id,sets:selected.sets,reps:selected.reps}]});setPlans([...plans,p]);setPlanId(p.id);setSelected(null);setLibrary(false);setPage('Workout');})}>Use in new workout <ChevronRight size={15}/></button></footer></div></div>}
 {summary&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-label="Workout saved"><header><div><span className="eyebrow">{summary.mode==='demo'?'DEMO SESSION SAVED':'WORKOUT SAVED'}</span><h2>One session stronger.</h2></div><button onClick={()=>setSummary(null)}>Close</button></header><div className="summary-strip"><Metric label="Reps" value={summary.summary.total_reps}/><Metric label="Time" value={fmtTime(summary.duration)}/><Metric label="Form" value={summary.summary.average_form??'—'}/></div>{summary.summary.insights?.map((x,i)=><p key={i}>{x}</p>)}<p className="tiny muted">{summary.mode==='demo'?'Synthetic demo results are excluded from camera workout progress.':'Your metrics are saved locally.'}</p><footer><button onClick={()=>{setSummary(null);setPage('History');}}>View history <ChevronRight size={16}/></button></footer></div></div>}
 </div>;
}
